create table status (
  "id" bigint generated by default as identity primary key,
  "nama" varchar not null,
  "createdAt" timestamp with time zone null default(now()),
  unique("nama")
);

create table instansi (
  "id" bigint generated by default as identity primary key,
  "nama" varchar not null,
  "alamat" text not null,
  "createdAt" timestamp with time zone null default(now()),
  unique("nama")
);

create table divisi (
  "id" bigint generated by default as identity primary key,
  "nama" varchar not null,
  "idInstansi" bigint not null references public.instansi,
  "createdAt" timestamp with time zone null default(now()),
  unique("nama", "idInstansi")
);

create table jabatan (
  "id" bigint generated by default as identity primary key,
  "nama" varchar not null,
  "idInstansi" bigint not null references public.instansi,
  "idDivisi" bigint not null references public.divisi,
  "createdAt" timestamp with time zone null default(now()),
  unique("nama", "idInstansi", "idDivisi")
);

